CREATE TABLE IF NOT EXISTS #SCHEMA.ITEM (
	I_OID VARCHAR NOT NULL PRIMARY KEY,
	I_TITLE VARCHAR,
	I_MAGNITUDE VARCHAR,
	I_TAGS VARCHAR ARRAY,
	I_VALUE FLOAT8,
	I_SOURCE VARCHAR,
	I_TIMESTAMP TIMESTAMP,
	I_LOCATION VARCHAR
);